angle_disable_max: 0
angle_disable_min: 0
angle3_disable_max: 0
angle3_disable_min: 0
channel_num: 0
frame_id: "laser_link"
frequency: 10.0
max_range: 150.0
min_range: 0.15
point_num: 2000
publish_point_cloud: true
publish_scan: true
use_gps_ts: false
